name: SuperNaturalPlayers
main: com.weeryan17.snp.Main
depend: [ProtocolLib]
version: 1.0
commands:
  howl:
    description: Werewolf command for howling
  bl:
    description: Vampire blood lust command
  bat:
    description: Vampire bat transformation command
  snp:
    description: Main admin command
  class:
    description: Claas command for giving info on your class.
  mob:
    description: Command for spawning mobs as a Necromancer
  wither:
    description: Necromancer wither transform command