name: SupernaturalPlayers
main: com.weeryan17.snp.Main
version: 1.2.0
commands:
  howl:
    description: Werewolf command for howling
  bl:
    description: Vampire blood lust command
  bat:
    description: Vampire bat transformation command
  snp:
    description: Main admin command
  class:
    description: Claas command for giving info on your class.
  mob:
    description: Command for spawning mobs as a Necromancer
  wither:
    description: Necromancer wither transform command
  clan:
    description: Command for clans(if the command doesn't work clans are dissabled)